---
- name: Simuler l'activation des services au démarrage
  hosts: localhost
  gather_facts: false

  vars:
    services:
      - name: nginx
      - name: apache2

  tasks:

    - name: Simuler l'activation de chaque service
      ansible.builtin.command: "echo Enabling service {{ item.name }}"
      loop: "{{ services }}"
      register: service_results
      changed_when: true  # Pour forcer l'état "changed", même si c'est un echo

    - name: Afficher les messages d'activation des services
      ansible.builtin.debug:
        msg: "Service {{ item.item.name }} activé"
      loop: "{{ service_results.results }}"
      loop_control:
        label: "{{ item.item.name }}"
