---
- name: Simulate enabling services at startup
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Simulate enabling services
      ansible.builtin.command: "{{ item.cmd }}"
      loop:
        - { cmd: "echo Enabling service nginx", msg: "Service nginx enabled" }
        - { cmd: "echo Enabling service apache2", msg: "Service apache2 enabled" }
      register: service_results

    - name: Display service activation messages
      ansible.builtin.debug:
        msg: "{{ item.item.msg }}"
      loop: "{{ service_results.results }}"
      loop_control:
        label: "{{ item.item.msg }}"
