---
- name: Déploiement simulé d’une infrastructure personnalisée
  hosts: all
  gather_facts: false

  vars:
    Reponse_1: "73"
    Reponse_2: "45"
    Reponse_3: "Nom_de_domaine"
    Reponse_4: "Oui"
    Reponse_5: "Non"
    Reponse_6: "Non"
    Reponse_7: "Oui"

  tasks:

    - name: Résumé situation
      debug:
        msg: |
          - Employés : {{ Reponse_1 }}
          - Postes : {{ Reponse_2 }}
          - Domaine : {{ Reponse_3 }}

    - name: Configuration du domaine (simulation)
      debug:
        msg: "Simulation de la configuration du domaine {{ Reponse_3 }}..."
      changed_when: true

    - name: Affichage résultat domaine
      debug:
        msg: "Domaine {{ Reponse_3 }} configuré (simulation)."

    - name: Gestion serveur FTP (simulation)
      debug:
        msg: |
          {% if Reponse_4 | lower == "oui" %}
          Simulation du déploiement du serveur FTP.
          {% else %}
          Pas de déploiement de serveur FTP nécessaire.
          {% endif %}
      changed_when: true

    - name: Gestion serveur Web (simulation)
      debug:
        msg: |
          {% if Reponse_5 | lower == "oui" %}
          Simulation du déploiement du serveur web.
          {% else %}
          Pas de déploiement de serveur Web nécessaire.
          {% endif %}
      changed_when: true

    - name: Gestion serveur Mail (simulation)
      debug:
        msg: |
          {% if Reponse_6 | lower == "oui" %}
          Simulation du déploiement du serveur mail.
          {% else %}
          Pas de déploiement de serveur mail nécessaire.
          {% endif %}
      changed_when: true

    - name: Gestion supervision (SIEM) (simulation)
      debug:
        msg: |
          {% if Reponse_7 | lower == "oui" %}
          Simulation du déploiement de la supervision avec Zabbix.
          {% else %}
          Pas de déploiement de SIEM nécessaire.
          {% endif %}
      changed_when: true

    - name: Résumé final de la simulation
      debug:
        msg: |
          Résumé des composants simulés :
          - Domaine : {{ Reponse_3 }}
          - FTP     : {{ 'Simulation déployée' if Reponse_4 | lower == 'oui' else 'Non déployé' }}
          - Web     : {{ 'Simulation déployée' if Reponse_5 | lower == 'oui' else 'Non déployé' }}
          - Mail    : {{ 'Simulation déployée' if Reponse_6 | lower == 'oui' else 'Non déployé' }}
          - SIEM    : {{ 'Simulation déployée' if Reponse_7 | lower == 'oui' else 'Non déployé' }}
      changed_when: true

    - name: Ajouts Jobs Administratifs (simulation)
      debug:
        msg: "Simulation de la création des jobs templates pour les tâches administratives."
      changed_when: true
