---
- name: Déploiement d’une infrastructure personnalisée
  hosts: all
  gather_facts: false

  vars:
    Reponse_1: "73"
    Reponse_2: "45"
    Reponse_3: "Nom_de_domaine"
    Reponse_4: "Oui"
    Reponse_5: "Non"
    Reponse_6: "Non"
    Reponse_7: "Oui"

  tasks:

    - name: Résumé situation
      debug:
        msg: |
          - Employés : {{ Reponse_1 }}
          - Postes : {{ Reponse_2 }}
          - Domaine : {{ Reponse_3 }}

    - name: Configuration du domaine
      debug:
        msg: |
          - Domaine configuré avec succès.
      changed_when: true

    - name: Affichage résultat domaine
      debug:
        msg: |
          - Domaine configuré : {{ Reponse_3 }}
          - Résultat : Configuré avec succès

    - name: Gestion serveur FTP
      debug:
        msg: |
          - Serveur FTP déployé (simulation).

      changed_when: true

    - name: Gestion serveur Web
      debug:
        msg: |
          - Serveur Web déployé.
      changed_when: true

    - name: Gestion serveur Mail
      debug:
        msg: |
          - Serveur Mail déployé .
      changed_when: true

    - name: Gestion supervision (SIEM)
      debug:
        msg: |
          - Supervision déployée avec Zabbix.
      changed_when: true

    - name: Résumé final
      debug:
        msg: |
          - Domaine : {{ Reponse_3 }}
          - FTP     : {{ 'Déployé' if Reponse_4 | lower == 'oui' else 'Non déployé' }}
          - Web     : {{ 'Déployé' if Reponse_5 | lower == 'oui' else 'Non déployé' }}
          - Mail    : {{ 'Déployé' if Reponse_6 | lower == 'oui' else 'Non déployé' }}
          - SIEM    : {{ 'Déployé' if Reponse_7 | lower == 'oui' else 'Non déployé' }}
      changed_when: true

    - name: Ajouts Jobs Administratifs
      debug:
        msg: "Création des jobs templates pour les tâches administratives."
      changed_when: true
