---
- name: Déploiement d’une infrastructure personnalisée
  hosts: all
  gather_facts: false

  vars:
    Reponse_1: "73"
    Reponse_2: "45"
    Reponse_3: "Nom_de_domaine"
    Reponse_4: "Oui"
    Reponse_5: "Non"
    Reponse_6: "Non"
    Reponse_7: "Oui"

  tasks:

    - name: Résumé situation
      shell: |
        echo "- Employés : {{ Reponse_1 }}"
        echo "- Postes : {{ Reponse_2 }}"
        echo "- Domaine : {{ Reponse_3 }}"
        sleep 1
      changed_when: true

    - name: Configuration du domaine
      shell: |
        echo "- Domaine configuré avec succès."
        sleep 1
      changed_when: true


    - name: Affichage résultat domaine
      shell: |
        echo "- Domaine configuré : {{ Reponse_3 }}"
        echo "- Résultat : Configuré avec succès"
        sleep 1
      changed_when: true

    - name: Gestion serveur FTP
      shell: |
        echo "- Serveur FTP déployé."
        sleep 1
      changed_when: true


    - name: Gestion serveur Web
      shell: |
        echo "- Serveur Web déployé."
        sleep 1
      changed_when: true


    - name: Gestion serveur Mail
      shell: |
        echo "- Serveur Mail déployé ."
        sleep 1
      changed_when: true


    - name: Gestion supervision (SIEM)
      shell: |
        echo "- Supervision déployée avec Zabbix."
        sleep 1
      changed_when: true


    - name: Résumé final
      shell: |
        echo "- Domaine : {{ Reponse_3 }}"
        echo "- FTP     : {{ 'Déployé' if Reponse_4 | lower == 'oui' else 'Non déployé' }}"
        echo "- Web     : {{ 'Déployé' if Reponse_5 | lower == 'oui' else 'Non déployé' }}"
        echo "- Mail    : {{ 'Déployé' if Reponse_6 | lower == 'oui' else 'Non déployé' }}"
        echo "- SIEM    : {{ 'Déployé' if Reponse_7 | lower == 'oui' else 'Non déployé' }}"
        sleep 1
      changed_when: true


    - name: Ajouts Jobs Administratifs
      shell: |
        echo "Création des jobs templates pour les tâches administratives."
        sleep 1
      changed_when: true
