---
- name: Déploiement simulé d’une infrastructure personnalisée
  hosts: all
  gather_facts: false

  vars:
    Reponse_1: "73"
    Reponse_2: "45"
    Reponse_3: "Nom_de_domaine"
    Reponse_4: "Oui"
    Reponse_5: "Non"
    Reponse_6: "Non"
    Reponse_7: "Oui"
    AWX_HOST: "http://127.0.0.1:8080"
    AWX_TOKEN: "yPLLeIEXMVoEImY2Qh0ixIG78puxQA"
    INVENTORY: "TPE-Inventaire"
    PROJECT: "SIMON"

  tasks:

    - name: Résumé situation
      debug:
        msg: |
          - Employés : {{ Reponse_1 }}
          - Postes : {{ Reponse_2 }}
          - Domaine : {{ Reponse_3 }}

    - name: Configuration du domaine
      shell: |
        echo "Configuration du domaine {{ Reponse_3 }}..."
        sleep 1
      register: domaine_result
      changed_when: true

    - name: Affichage résultat domaine
      debug:
        var: domaine_result.stdout

    - name: Gestion serveur FTP
      shell: |
        {% if Reponse_4 | lower == "oui" %}
        echo "Besoin de partage de fichiers détecté : déploiement du serveur FTP."
        sleep 1
        {% else %}
        echo "Aucun besoin de partage massif de fichiers : pas de serveur FTP déployé "
        {% endif %}
      register: ftp_result
      changed_when: true

    - name: Gestion serveur Web 
      shell: |
        {% if Reponse_5 | lower == "oui" %}
        echo "Site web requis : déploiement du serveur web."
        sleep 1
        {% else %}
        echo "Pas de site web demandé : aucun serveur web déployé "
        {% endif %}
      register: web_result
      changed_when: true

    - name: Gestion serveur Mail 
      shell: |
        {% if Reponse_6 | lower == "oui" %}
        echo "Échange de mails requis : déploiement du serveur mail."
        sleep 1
        {% else %}
        echo "Pas de service mail requis : aucun serveur mail déployé "
        {% endif %}
      register: mail_result
      changed_when: true

    - name: Gestion supervision (SIEM)
      shell: |
        {% if Reponse_7 | lower == "oui" %}
        echo "Supervision requise : déploiement de Zabbix + agents."
        sleep 1
        {% else %}
        echo "Pas de supervision nécessaire : SIEM non déployé "
        {% endif %}
      register: siem_result
      changed_when: true

    - name: Résumé final
      debug:
        msg: |
          Résumé des composants simulés :
          - Domaine : {{ Reponse_3 }}
          - FTP     : {{ 'Déployé' if Reponse_4 | lower == 'oui' else 'Non déployé ' }}
          - Web     : {{ 'Déployé' if Reponse_5 | lower == 'oui' else 'Non déployé ' }}
          - Mail    : {{ 'Déployé' if Reponse_6 | lower == 'oui' else 'Non déployé ' }}
          - SIEM    : {{ 'Déployé' if Reponse_7 | lower == 'oui' else 'Non déployé ' }}

    - name: Ajouts Jobs Administratifs
      shell: |
        whoami
      register: awx_result
      changed_when: true

    - name: Résultat Ajout
      debug:
        var: awx_result.stdout
