---
- name: Réinitialisation du mot de passe utilisateur
  hosts: all
  gather_facts: false

  vars:
    username: "utilisateur"
    new_password: "Ch@ngeMe123!"

  tasks:

    - name: [1/3] Vérification de l’utilisateur {{ username }}
      shell: |
        echo "Recherche de l’utilisateur {{ username }} dans le système..."
        sleep 1
      changed_when: true

    - name: [2/3] Réinitialisation du mot de passe
      shell: |
        echo "Modification du mot de passe pour {{ username }} avec la commande :"
        echo "echo '{{ new_password }}' | passwd --stdin {{ username }} (simulation)"
        sleep 1
      changed_when: true

    - name: [3/3] Mot de passe de {{ username }} réinitialisé avec succès
      shell: |
        echo "Le mot de passe pour {{ username }} a été mis à jour."
      changed_when: false
